'use client'

interface Props {
  html: string
}

export default function AIReport({ html }: Props) {
  if (!html) return null

  return (
    <div className="text-sm text-[#CBD5E1] leading-relaxed">
      <style>{`
        .ai-report h4 {
          font-family: 'Crimson Pro', Georgia, serif;
          font-size: 0.9rem;
          font-weight: 600;
          color: #F8FAFC;
          margin: 12px 0 6px;
        }
        .ai-report ul {
          margin: 0 0 8px 0;
          padding-left: 16px;
        }
        .ai-report li {
          margin-bottom: 4px;
          color: #CBD5E1;
          line-height: 1.55;
        }
      `}</style>
      <div
        className="ai-report"
        // HTML generated by our own LLM pipeline (h4/ul/li only)
        // eslint-disable-next-line react/no-danger
        dangerouslySetInnerHTML={{ __html: html }}
      />
    </div>
  )
}
