"use client";

interface Props {
  html: string;
}

export default function AIReport({ html }: Props) {
  if (!html) return null;

  return (
    <div className="text-sm text-primary leading-relaxed">
      <div
        className="ai-report"
        // HTML generated by our own LLM pipeline (h4/ul/li only)
        dangerouslySetInnerHTML={{ __html: html }}
      />
    </div>
  );
}
