import { notFound } from 'next/navigation'
import { loadGraphData } from '@/lib/store'
import GraphViewer from '@/components/GraphViewer'

interface Props {
  params: Promise<{ id: string }>
}

export default async function AnalysisPage({ params }: Props) {
  const { id } = await params
  const graph = loadGraphData(id)

  if (!graph) {
    notFound()
  }

  const { nodes, edges, stats, communities, ai_report, generated_at } = graph

  const generatedTw = new Date(generated_at).toLocaleString('zh-TW', {
    timeZone: 'Asia/Taipei',
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
  })

  return (
    <main style={{ background: '#020617', minHeight: '100vh', color: '#F8FAFC' }}>
      {/* Header */}
      <header
        style={{
          background: '#0F172A',
          borderBottom: '1px solid #334155',
          padding: '16px 24px',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          flexWrap: 'wrap',
          gap: '12px',
        }}
      >
        <div>
          <h1
            style={{
              fontFamily: "'Crimson Pro', Georgia, serif",
              fontSize: '1.5rem',
              fontWeight: 700,
              color: '#F8FAFC',
              lineHeight: 1.3,
            }}
          >
            專利知識圖譜分析
          </h1>
          <p style={{ fontSize: '0.8rem', color: '#94A3B8', marginTop: '4px' }}>
            Job ID: {id} · 產生於 {generatedTw} (UTC+8)
          </p>
        </div>

        <a
          href={`/api/export/${id}`}
          aria-label="下載離線 HTML 圖譜"
          style={{
            background: '#1E293B',
            border: '1px solid #334155',
            borderRadius: '6px',
            padding: '8px 16px',
            color: '#F8FAFC',
            fontSize: '0.875rem',
            textDecoration: 'none',
          }}
        >
          下載離線 HTML
        </a>
      </header>

      <div style={{ maxWidth: '1400px', margin: '0 auto', padding: '32px 24px' }}>

        {/* Stats row */}
        <section
          aria-label="圖譜統計"
          style={{ display: 'flex', gap: '16px', flexWrap: 'wrap', marginBottom: '32px' }}
        >
          {[
            { label: '申請人', value: stats.applicant_count },
            { label: '專利', value: stats.patent_count },
            { label: '技術概念', value: stats.concept_count },
            { label: '社群', value: stats.community_count },
            {
              label: '年份範圍',
              value: `${stats.year_range[0]} – ${stats.year_range[1]}`,
            },
          ].map((item) => (
            <div
              key={item.label}
              style={{
                background: '#1E293B',
                border: '1px solid #334155',
                borderRadius: '8px',
                padding: '16px 20px',
                minWidth: '120px',
              }}
            >
              <div
                style={{
                  fontSize: '1.5rem',
                  fontWeight: 700,
                  color: '#4E79A7',
                  fontFamily: "'Crimson Pro', Georgia, serif",
                }}
              >
                {item.value}
              </div>
              <div style={{ fontSize: '0.8rem', color: '#94A3B8', marginTop: '4px' }}>
                {item.label}
              </div>
            </div>
          ))}
        </section>

        {/* Graph canvas — client-side vis-network */}
        <section aria-label="互動式圖譜" style={{ marginBottom: '32px' }}>
          <h2
            style={{
              fontFamily: "'Crimson Pro', Georgia, serif",
              fontSize: '1.25rem',
              fontWeight: 600,
              marginBottom: '12px',
              color: '#F8FAFC',
            }}
          >
            互動式知識圖譜
          </h2>
          <GraphViewer nodes={nodes} edges={edges} communities={communities} />
        </section>

        {/* AI report */}
        {ai_report && (
          <section aria-label="AI 趨勢報告" style={{ marginBottom: '32px' }}>
            <h2
              style={{
                fontFamily: "'Crimson Pro', Georgia, serif",
                fontSize: '1.25rem',
                fontWeight: 600,
                marginBottom: '12px',
                color: '#F8FAFC',
              }}
            >
              AI 趨勢報告
            </h2>
            <div
              style={{
                background: '#1E293B',
                border: '1px solid #334155',
                borderRadius: '8px',
                padding: '20px 24px',
                lineHeight: 1.7,
                fontSize: '0.95rem',
                color: '#F8FAFC',
                maxWidth: '72ch',
              }}
              // HTML is generated by our own LLM pipeline (h4/ul/li only)
              // eslint-disable-next-line react/no-danger
              dangerouslySetInnerHTML={{ __html: ai_report }}
            />
          </section>
        )}

      </div>
    </main>
  )
}
